site_name: libib-client
repo_url: https://github.com/michael-masarik/libib-client
edit_uri: https://github.com/michael-masarik/libib-client/edit/main/docs/
site_author: Michael Masarik
site_description: Docs for libib-client, a synchronous, third-party client for the Libib API
copyright: "Â© 2026 Michael Masarik. Licensed under MIT."
nav:
  - Home: index.md
  - Patrons: Patrons.md
  - Managers: Managers.md
  - Accounts: Accounts.md
theme:
  name: mkdocs
  user_color_mode_toggle: true

  